repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.1
  hooks:
    - id: mypy
      additional_dependencies:
        - httpx
        - pillow
        - playsound3
        - numpy
        - pygame
      args: [--config-file=pyproject.toml]
