name: Merge Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  merge-request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      run: pip install uv

    - name: Install dependencies with uv
      run: uv sync

    - name: Lint with ruff
      run: uv run ruff check

    - name: Format with ruff
      run: uv run ruff format --check

    - name: Typecheck with mypy
      run: uv run mypy .

    - name: Test with pytest
      run: uv run pytest
